### ISSUE TITLE
Key API Kaggle

### ISSUE THREAD

**Issue by wildangunawan** [shfjri/Project_UTS_FGA#1]
Halo mas/mbak.

Di dalam repository ini ada file kaggle.json yang ada key API Kaggle punya mas/mbak. Saya belum coba apakah keynya masih nyala atau nggak. Saya cuman mau kasih tau itu aja sih, barangkali mas/mbak belum revoke keynya dan masih "nyala" sehingga membahayakan akun Kaggle mas/mbaknya juga.

Terima kasih banyak ;).

**Comment by shfjri** [comment]
Selamat malam

Terima kasih sudah mengingatkan tentang kaggle api di salah satu repo saya.
Saya bahkan lupa kalo file jsonnya juga kepush. Sudah saya delete dan
revoke tokennya. Sekali lagi, terima kasih banyak sudah mengingatkan :)

**Comment by wildangunawan** [comment]
Okey ;)
